### ISSUE TITLE
Error: Request contains invalid set of changes for resource record set CNAME

### ISSUE THREAD

**Issue by corydorning53** [schwamster/serverless-certificate-creator#28]
When I run `sls create-cert` I get the following error:
```
Serverless: Trying to create certificate for my.domain.com in us-east-2 ...
Serverless: requested cert: arn:aws:acm:us-east-2:ACCT_ID:certificate/f5c5b0a7-8e8f-4adf-8db6-790aa0d471a8
Serverless: got cert info: arn:aws:acm:us-east-2:ACCT_ID:certificate/f5c5b0a7-8e8f-4adf-8db6-790aa0d471a8 - PENDING_VALIDATION
InvalidChangeBatch: [The request contains an invalid set of changes for a resource record set 'CNAME _75ec2cb563eb518da1b6227f7a5a7d9c.my.domain.com.']: could not create record set for dns validation
problem InvalidChangeBatch: [The request contains an invalid set of changes for a resource record set 'CNAME _75ec2cb563eb518da1b6227f7a5a7d9c.my.domain.com.']
    at Request.extractError (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (events.js:228:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  message: "[The request contains an invalid set of changes for a resource record set 'CNAME _75ec2cb563eb518da1b6227f7a5a7d9c.my.domain.com.']",
  code: 'InvalidChangeBatch',
  time: 2020-10-07T17:48:39.980Z,
  requestId: '8d51f0a5-9cc6-4822-8061-b79127981ed3',
  statusCode: 400,
  retryable: false,
  retryDelay: 58.69370577818556
}
```

My settings are as follows:
```
customCertificate:
    certificateName: my.domain.com
    hostedZoneIds: MY_ZONE_ID
    region: ${self:provider.region}
    subjectAlternativeNames: 
      - '*.my.domain.com'
    tags:
      Name: my.domain
      Environment: ${self:provider.stage}
    rewriteRecords: true
```

**Comment by corydorning53** [comment]
Issue was with the way i was formatting `subjectAlternativeNames`

**Comment by jessgoldq4** [comment]
Getting the same error. @corydorning53 @schwamster How are you supposed to format them exactly? Mine look like yours. Thanks
