### ISSUE TITLE
Plugin is throwing "TypeError: Cannot read property 'enabled' of undefined" errors

### ISSUE THREAD

**Issue by G-Rath** [schwamster/serverless-certificate-creator#36]
I love the look of this plugin, as it seems like it'd do exactly what I want (aka, create a validated cert in `us-east-1` with no strings attached), but it seems to be throwing an error whenever I try to use it.

If I just add the plugin and then run a command such as `sls create-cert` or `sls deploy`, I get this:

```
TypeError: Cannot read property 'enabled' of undefined
      at CreateCertificatePlugin.evaluateEnabled (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/serverless-certificate-creator/index.js:95:70)
      at CreateCertificatePlugin.initializeVariables (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/serverless-certificate-creator/index.js:54:27)
      at CreateCertificatePlugin.createCertificate (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/serverless-certificate-creator/index.js:208:10)
      at /c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/serverless/lib/classes/PluginManager.js:518:55
      at tryCatcher (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/c/Users/G-Rath/workspace/te/serverless-aws-template/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:461:21)
```

I was originally getting the same error for a `CertificateArn` property when I had `customCertificate` defined, but it seems the underlying error is that the `this` isn't being set properly since just adding the plugin causes the above to be thrown.

I can reproduce this using my company's [serverless template repo](
https://github.com/ackama/serverless-aws-template), by just installing the plugin and adding it to the `plugins` list (you'll also need to set `unresolvedVariablesNotificationMode` to `warn` just so it doesn't error on the env variables).

I've tried this with the latest version of `serverless` too, with no difference.

I've not had the time yet to look into this further, but am happy to help where I can :)

**Comment by schwamster** [comment]
Awesome @G-Rath  thank you very much!

https://github.com/schwamster/serverless-certificate-creator/releases/tag/v1.5.2

Will get back to you about the contributor offer soon :) Could really use some help. There are a bunch of things that should be done.
