### ISSUE TITLE
Broken on sls 2.30.0 (works on 2.29.0)

### ISSUE THREAD

**Issue by ColdFire87** [schwamster/serverless-certificate-creator#39]
The plugin breaks on the latest version of The Serverless Framework (`2.30.0`) with the following error:

```
TypeError: Cannot read property 'Route53' of undefined
      at CreateCertificatePlugin.initializeVariables (...\node_modules\serverless-certificate-creator\index.js:70:62)
      at CreateCertificatePlugin.createCertificate (...\node_modules\serverless-certificate-creator\index.js:227:10)
      at PluginManager.invoke (...\node_modules\serverless\lib\classes\PluginManager.js:541:20)
      at ...\node_modules\serverless\lib\classes\PluginManager.js:576:24
      at tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (...\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (...\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (...\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (...\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (...\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (...\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (...\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues (...\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

![image](https://user-images.githubusercontent.com/14059086/111322653-0e9c3500-8661-11eb-8052-8699f4d219a4.png)

It seems to be working fine on sls `2.29.0`, so it's probably due to a change they introduced. Maybe it's a bug in sls, I thought I should raise the issue here rather than the sls repo.

**Comment by schwamster** [comment]
thanks @ColdFire87 for reporting. Will check it out as soon as I find the time.

**Comment by coyoteecd** [comment]
@ColdFire87 this has been solved in serverless v2.30.2, see https://github.com/serverless/serverless/issues/9126.
But it will become an issue sooner or later, since they want to deprecate that property.
